---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  is_file_root: true
  salt_file_root: /srv/salt/salt
  salt_run_highstate: true

platforms:
  - name: centos-7.2
    driver_config:
      run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - gtmanfred
        gtmanfred.sls:
          gtmanfred:
            user: pelican
            venv: /home/pelican/gtmanfred
            proj: /home/pelican/gtmanfred/site
            theme: /home/pelican/gtmanfred/site/themes/pelican-bootstrap3
            url: blog.gtmanfred.com
            root: /home/pelican/gtmanfred/site/output

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
