language: python
python:
- 3.6
services:
- docker
install:
- bundle install
- pip install pipenv
- pipenv install --deploy
script:
- bundle exec kitchen test
notifications:
  webhooks: 
    urls:
      - https://blog.gtmanfred.com/hook/update/blog-sls/travis
    on_success: always
