sudo: required
language: ruby
services:
- docker
before_install:
- pip install -r requirements.txt
script:
- bundle exec kitchen verify
notifications:
  webhooks: 
    urls:
      - https://blog.gtmanfred.com/hook/update/blog-sls/travis
    on_success: always
