---
driver:
  name: docker
  use_sudo: false
  privileged: true
  forward:
    - 80

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  salt_run_highstate: true
  is_file_root: true
  state_top:
    base:
      '*':
        - nginx
        - gtmanfred.app
        - wedding
        - vim
        - ssh
        - firewalld

platforms:
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - gtmanfred
        gtmanfred.sls:
          gtmanfred:
            user: pelican
            venv: /home/pelican/gtmanfred
            proj: /home/pelican/gtmanfred/site
            themes: /home/pelican/gtmanfred/site/themes/
            plugins: /home/pelican/gtmanfred/site/plugins/
            url: blog.gtmanfred.com
            root: /home/pelican/gtmanfred/site/output

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID test/integration/$KITCHEN_SUITE
